gText_Birch_Welcome::
# 1 "data/text/birch_speech.pory"
	.string "¡Hola! Me llamo Birch.\p"
	.string "Pero todos me conocen como Profesor.\p"
	.string "$"

gText_Birch_Pokemon::
# 12 "data/text/birch_speech.pory"
	.string "\p$"

gText_Birch_Pronouns::
# 16 "data/text/birch_speech.pory"
	.string "¿Cómo te gustaría que\n"
	.string "se refiriesen a tí?$"

gText_Birch_MainSpeech::
# 27 "data/text/birch_speech.pory"
	.string "Me apasionan…\n"
	.string "Por eso, he dedicado mi vida a\l"
	.string "estudiarlos a fondo…\p"
	.string "¡Pero suficiente de mí!\p"
	.string "$"

gText_Birch_AndYouAre::
# 38 "data/text/birch_speech.pory"
	.string "¿A quién te pareces más?\p"
	.string "$"

gText_Birch_BoyOrGirl::
# 49 "data/text/birch_speech.pory"
	.string "¿A Brendan o May?$"

gText_Birch_WhatsYourName::
# 60 "data/text/birch_speech.pory"
	.string "¡Genial!\n"
	.string "¿Qué nombre te gustaría usar?$"

gText_Birch_SoItsPlayer::
# 71 "data/text/birch_speech.pory"
	.string "¿{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
# 83 "data/text/birch_speech.pory"
	.string "¡Perfecto! ¡Eres {PLAYER}, y te\n"
	.string "mudaste aquí desde Johto!\p"
	.string "$"

gText_Birch_AreYouReady::
# 94 "data/text/birch_speech.pory"
	.string "Tu propia aventura comenzará.\n"
	.string "Conocerás personas, Pokémon, e\l"
	.string "historias de lo más variadas…\p"
	.string "¡Adéntrate ahora, al Mundo Pokémon!\p"
	.string "$"

gText_Birch_YouCantBirch::
# 107 "data/text/birch_speech.pory"
	.string "N-no…\pEse… Ese es MI nombre…\pElige otro nombre.$"

gText_Birch_WaitYoureG::
# 111 "data/text/birch_speech.pory"
	.string "E-eres… ¿{PLAYER}?\p¡Genial, yo soy bi!\pPero ahora, por favor, escribe un nombre…\pA menos que quieras que te digan así.\p¿Quieres llamarte {PLAYER}?$"

gText_Birch_TheSameAsDaughter::
# 115 "data/text/birch_speech.pory"
	.string "¡Ah, igual que mi hija entonces!\pEspero no confunda…\n¿{PLAYER} te parece bien?$"

gText_Birch_TheSameAsSon::
# 119 "data/text/birch_speech.pory"
	.string "¡Ah, igual que mi hijo entonces!\pEspero no confunda…\n¿{PLAYER} te parece bien?$"

gText_Birch_NotVeryOriginal::
# 123 "data/text/birch_speech.pory"
	.string "Ah, ¡{PLAYER}, entonces!\pUn nombre muy popular.\p¿{PLAYER} te parece bien?$"
