gText_Birch_Welcome::
# 1 "data/text/birch_speech.pory"
	.string "¡Hola! Me llamo Birch.\p"
	.string "Pero todos me conocen como Profesor.\p"
	.string "$"

gText_Birch_Pokemon::
# 12 "data/text/birch_speech.pory"
	.string "\p$"

gText_Birch_Pronouns::
# 16 "data/text/birch_speech.pory"
	.string "¿Cómo te gustaría que\n"
	.string "se refiriesen a tí?$"

gText_Birch_MainSpeech::
# 27 "data/text/birch_speech.pory"
	.string "Me apasionan…\n"
	.string "Por eso, he dedicado mi vida a\l"
	.string "estudiarlos a fondo…\p"
	.string "¡Pero suficiente de mí!\p"
	.string "$"

gText_Birch_AndYouAre::
# 38 "data/text/birch_speech.pory"
	.string "¿A quién te pareces más?\p"
	.string "$"

gText_Birch_BoyOrGirl::
# 49 "data/text/birch_speech.pory"
	.string "¿A Brendan o May?$"

gText_Birch_WhatsYourName::
# 60 "data/text/birch_speech.pory"
	.string "¡Genial!\n"
	.string "¿Qué nombre te gustaría usar?$"

gText_Birch_SoItsPlayer::
# 71 "data/text/birch_speech.pory"
	.string "¿{PLAYER}?$"

gText_Birch_YourePlayer::
# 83 "data/text/birch_speech.pory"
	.string "¡Perfecto! ¡Eres {PLAYER}, y te\n"
	.string "mudaste aquí desde Johto!\p"
	.string "$"

gText_Birch_AreYouReady::
# 94 "data/text/birch_speech.pory"
	.string "Tu propia aventura comenzará.\n"
	.string "Conocerás personas, Pokémon, e\l"
	.string "historias de lo más variadas…\p"
	.string "¡Adéntrate ahora, al Mundo Pokémon!\p"
	.string "$"

gText_Birch_YouCantBirch::
# 107 "data/text/birch_speech.pory"
	.string "N-no…\p"
	.string "Ese… Ese es MI nombre…\p"
	.string "Elige otro nombre.$"

gText_Birch_WaitYoureG::
# 118 "data/text/birch_speech.pory"
	.string "E-eres… ¿{PLAYER}?\p"
	.string "¡Genial, yo soy bi!\p"
	.string "Pero ahora, por favor, escribe un\n"
	.string "nombre…\p"
	.string "A menos que quieras que te digan así.\p"
	.string "¿Quieres llamarte {PLAYER}?$"

gText_Birch_TheSameAsDaughter::
# 132 "data/text/birch_speech.pory"
	.string "¡Ah, igual que mi hija entonces!\p"
	.string "Espero no confunda…\n"
	.string "¿{PLAYER} te parece bien?$"

gText_Birch_TheSameAsSon::
# 143 "data/text/birch_speech.pory"
	.string "¡Ah, igual que mi hijo entonces!\p"
	.string "Espero no confunda…\n"
	.string "¿{PLAYER} te parece bien?$"

gText_Birch_NotVeryOriginal::
# 154 "data/text/birch_speech.pory"
	.string "Ah, ¡{PLAYER}, entonces!\p"
	.string "¿No estamos muy originales hoy, eh?\p"
	.string "¿{PLAYER} te parece bien?$"
