# 453 "data/text/story_dialogue.pory"


SlateportCity_SternsShipyard_1F_Text_CantMakeHeadsOrTails::
# 2 "data/text/story_dialogue.pory"
	.string "A ver… Si esto va aquí y aquello va allá…\p"
	.string "¿Dónde va esto entonces?\n"
	.string "¡Ahhh! ¡Ese tipo y su letra de doctor!$"

SlateportCity_SternsShipyard_1F_Text_MeetDockDeliverToStern::
# 18 "data/text/story_dialogue.pory"
	.string "¿Eh?\n"
	.string "Ah, hola, soy Dock Muéllez.\p"
	.string "El Capitán Stern me ha encargado que\n"
	.string "diseñe un ferry.\p"
	.string "Oh, eso de ahí…\n"
	.string "¿Son las Partes Devon?\p"
	.string "Deben ser para él. El tipo las NECESITA,\n"
	.string "no paraba de murmurarlo.\p"
	.string "¿Puedes ir a buscarlo? Creo que andaba\n"
	.string "por el Museo Océanico buscando\l"
	.string "inspiración.$"

SlateportCity_SternsShipyard_1F_Text_CouldYouFindStern::
# 38 "data/text/story_dialogue.pory"
	.string "¿Que adónde puede haber ido el\n"
	.string "Capitán?\p"
	.string "¿Podrías ir a buscarlo y entregarle ese\n"
	.string "paquete?$"

SlateportCity_SternsShipyard_1F_Text_CouldUseAdviceFromVeteran::
# 54 "data/text/story_dialogue.pory"
	.string "Construir barcos es todo un arte.\p"
	.string "Hay mucho que no se resolver con\n"
	.string "cálculos.\p"
	.string "Cómo me gustaría que algún lindo lobo\n"
	.string "de mar me aconsejase…$"

SlateportCity_SternsShipyard_1F_Text_BrineyJoinedUs::
# 70 "data/text/story_dialogue.pory"
	.string "¡Hola! El Señor Briney se ha unido a\n"
	.string "nosotros.\p"
	.string "Gracias a su valiosísima ayuda, nuestro\n"
	.string "proyecto de ferry empieza a tomar\l"
	.string "forma.$"

SlateportCity_SternsShipyard_1F_Text_FerryIsReady::
# 86 "data/text/story_dialogue.pory"
	.string "¡El ferry está listo!\p"
	.string "¡El nuevo S.S. MAREA es toda una\n"
	.string "maravilla tecnológica!\p"
	.string "Sin embargo, creo que aún podemos\n"
	.string "mejorar el diseño.\p"
	.string "¡Ya sabes que el avance de la ciencia es\n"
	.string "imparable!$"

SlateportCity_SternsShipyard_1F_Text_DecidedToHelpDock::
# 107 "data/text/story_dialogue.pory"
	.string "¡Anda, {PLAYER}{KUN}!\n"
	.string "¡Cuánto tiempo!\p"
	.string "Desde que te conocí, me he\n"
	.string "sentido la mar de inquieto.\p"
	.string "Así que he decidido ayudar a\n"
	.string "MUÉLLEZ a construir el ferry.\p"
	.string "¡Imagina cuánta gente podría\n"
	.string "transportar en cada viaje!\p"
	.string "¿Sabes? Este MUÉLLEZ es\n"
	.string "un tipo especial de verdad.\p"
	.string "Uniendo sus conocimientos\n"
	.string "y mi experiencia, haremos\l"
	.string "un gran barco, ¡ya lo creo!$"

SlateportCity_SternsShipyard_1F_Text_SeaIsLikeLivingThing::
# 142 "data/text/story_dialogue.pory"
	.string "Las estaciones, el tiempo,\n"
	.string "la posición de la Luna…\p"
	.string "El estado del mar se ve afectado\n"
	.string "por todo esto y mucho más.\p"
	.string "¡Exactamente!\n"
	.string "¡El mar tiene vida!$"

SlateportCity_SternsShipyard_1F_Text_GetSeasickEasily::
# 164 "data/text/story_dialogue.pory"
	.string "Me entra mareo con nada…, así que\n"
	.string "me han destinado a este puesto.$"

SlateportCity_OceanicMuseum_2F_Text_ShouldI::
# 177 "data/text/story_dialogue.pory"
	.string "{COLOR BLUE}(¿Debería dárselas...?)\p"
	.string "(Supongo que no hay de otra, dejando\n"
	.string "dudas de lado.){COLOR DARK_GRAY}$"

SlateportCity_OceanicMuseum_2F_Text_WeCantDoThat::
# 181 "data/text/story_dialogue.pory"
	.string "¡Tienes sólo un Pokémon!\p"
	.string "¡No podemos atacar a alguien así!$"

SlateportCity_OceanicMuseum_2F_Text_WeCantBeatUp::
# 185 "data/text/story_dialogue.pory"
	.string "¿Lo habrá hecho a propósito?\n"
	.string "¿Para que no l{OA} ataquen?\p"
	.string "¡Arceus, ¿qué pensará el Jefe?!\n"
	.string "¡Esas Partes son nuestras!$"

SlateportCity_OceanicMuseum_2F_Text_BeReady::
# 189 "data/text/story_dialogue.pory"
	.string "Okay, Stern, cálmate. Todo estará bien...$"

SlateportCity_OceanicMuseum_2F_Text_ThankYouForTheParts::
# 193 "data/text/story_dialogue.pory"
	.string "Ah, hola, ¿Eres {ELLA} repartidor{A}?\n"
	.string "Puedes dejarme las Partes por ahí, este\l"
	.string "lugar es peligroso ahora.$"

SlateportCity_OceanicMuseum_2F_Text_WellTakeThoseParts::
# 198 "data/text/story_dialogue.pory"
	.string "{COLOR LIGHT_GRAY SHADOW WHITE}¿Cómo era? Ah, sí, ok. {COLOR DARK_GRAY SHADOW LIGHT_GRAY}\p"
	.string "¡Alto ahí, señores!\n"
	.string "¡Nos llevaremos esas Partes!$"

SlateportCity_OceanicMuseum_2F_Text_SternWhoAreYou::
# 203 "data/text/story_dialogue.pory"
	.string "¡Oh! ¡Eh! ¿Qué?\n"
	.string "¿Q-quiénes son?$"

SlateportCity_OceanicMuseum_2F_Text_WereTeamAqua::
# 208 "data/text/story_dialogue.pory"
	.string "¡Somos el Equipo Aqua!\p"
	.string "¡Y nuestro Jefe nos envió a buscar esas\n"
	.string "Partes!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt1Defeat::
# 213 "data/text/story_dialogue.pory"
	.string "¡Aaaahh!\n"
	.string "¡Me ganó un{A} niñ{OA}!$"

SlateportCity_OceanicMuseum_2F_Text_BossGoingToBeFurious::
# 218 "data/text/story_dialogue.pory"
	.string "¿Porqué tenía que pasar esto…?\n"
	.string "El Jefe no estará complacido…$"

SlateportCity_OceanicMuseum_2F_Text_LetMeTakeCareOfThis::
# 223 "data/text/story_dialogue.pory"
	.string "¡Pedazo de idiota!\n"
	.string "¡Se suponía que atacáramos juntos!\p"
	.string "¡Ven conmigo, aún con esos Pokémon\n"
	.string "débiles de tus reservas seremos más\l"
	.string "fuertes!$"

SlateportCity_OceanicMuseum_2F_Text_LetMeTakeCareOfThis2::
# 228 "data/text/story_dialogue.pory"
	.string "¡Prerárate!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt2Defeat::
# 232 "data/text/story_dialogue.pory"
	.string "Recluta 1: ¡¿QUÉ?!\n"
	.string "Recluta 2: ¡Ja! El problema\l"
	.string "no era yo.$"

SlateportCity_OceanicMuseum_2F_Text_MeddlingKid::
# 237 "data/text/story_dialogue.pory"
	.string "¿Ahora qué? Se supone que las Partes\n"
	.string "son nuestras, ¡Esto es injusto!$"

SlateportCity_OceanicMuseum_2F_Text_CameToSeeWhatsTakingSoLong::
# 242 "data/text/story_dialogue.pory"
	.string "Sabía que no se podía confiar en Stern,\n"
	.string "¿pero en ustedes?\p"
	.string "¡No pensé que perderían ante un{A} niñ{OA}!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWarning::
# 247 "data/text/story_dialogue.pory"
	.string "¡Escúchame bien, vamos a cambiar el\n"
	.string "mundo!\p"
	.string "¡Yo, {COLOR BLUE}el Líder del Equipo{COLOR DARK_GRAY},\n"
	.string "{COLOR BLUE}el Grandioso Archie{COLOR DARK_GRAY}, te lo aseguro!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWarning2::
# 252 "data/text/story_dialogue.pory"
	.string "En pocos años, llegaremos {COLOR BLUE}a un punto\n"
	.string "sin retorno{COLOR DARK_GRAY}, uno donde nuestras\l"
	.string "acciones dejarán este mundo\l"
	.string "inhabitable.\p"
	.string "Todos aquí en Slateport lo saben, ¡Pero\n"
	.string "mi Equipo Aqua salvará el mundo!\p"
	.string "Tengo que admitirlo…\p"
	.string "Tienes agallas por meterte con\n"
	.string "nosotros, ¡Pero para la próxima, te\l"
	.string "dejaré naufragando!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWereLeaving::
# 257 "data/text/story_dialogue.pory"
	.string "¡Ahora, ustedes dos!\n"
	.string "¡Nos vamos!\p"
	.string "Díganle a todos que nos vamos a las\n"
	.string "aguas termales, lo merecen.\p"
	.string "Algo me dice que ya recuperaremos las\n"
	.string "Partes.$"

SlateportCity_OceanicMuseum_2F_Text_SternThankYouForSavingUs::
# 263 "data/text/story_dialogue.pory"
	.string "Ese {COLOR BLUE}Equipo Aqua{COLOR DARK_GRAY}… …\n"
	.string "¡Entrar a la fuerza y atacar a un{A} niñ{OA}!\p"
	.string "No puedo creer que esta ciudad esté\n"
	.string "tan de acuerdo con criminales que dicen\l"
	.string "“ayudar,”\l"
	.string "¡Cuando en verdad son un peligro!\p"
	.string "Pero bueno, ¡Me llevaré las Partes,\n"
	.string "gracias!$"

SlateportCity_OceanicMuseum_2F_Text_SternIveGotToGo::
# 271 "data/text/story_dialogue.pory"
	.string "Estas Partes son necesarias para la\n"
	.string "construcción de un {COLOR BLUE}submarino{COLOR DARK_GRAY} que\l"
	.string "inventé…$"

MauvilleCity_Text_UncleHesTooPeppy::
# 278 "data/text/story_dialogue.pory"
	.string "Mi Wally se emociona mucho, gracias a\n"
	.string "los Pokémon.\p"
	.string "Me parece que es mucha emoción…$"

MauvilleCity_Text_WallyWantToChallengeGym::
# 284 "data/text/story_dialogue.pory"
	.string "¡Ay, porfa, Tío, déjame tomar el {COLOR BLUE}Desafío\n"
	.string "de los Gimnasios{COLOR DARK_GRAY}, ya soy muy fuerte!\p"
	.string "¡Ralts y yo aprendimos técnicas súper\n"
	.string "fuertes!$"

MauvilleCity_Text_UncleYourePushingIt::
# 291 "data/text/story_dialogue.pory"
	.string "Wally, Wally, tranquilo.\p"
	.string "¿No te estás precipitando?{PAUSE 2} Entiendo\n"
	.string "que se hayan fortalecido, pero los\l"
	.string "{COLOR BLUE}Líderes de Gimnasio{COLOR DARK_GRAY} son MUY fuertes…$"

MauvilleCity_Text_WallyWeCanBeatAnyone::
# 298 "data/text/story_dialogue.pory"
	.string "¡No me estoy precipitando, Tío!\p"
	.string "Si Ralts me ayuda, {PAUSE 5}¡Podré vencer a\n"
	.string "cualquier rival!$"

MauvilleCity_Text_WallyWillYouBattleMe::
# 304 "data/text/story_dialogue.pory"
	.string "Ah, {PAUSE 2}¡{PLAYER}, {PLAYER}!\p"
	.string "¡Hace tanto que no te veo, amig{OA}!\p"
	.string "¡{PLAYER}, {PLAYER}, quiero\n"
	.string "mostrarte lo fuerte que me he vuelto!\l"
	.string "Mi Ralts hasta ha aprendido muchos\l"
	.string "ataques nuevos, {PLAYER}.\p"
	.string "¿Te gustaría combatir conmigo,\n"
	.string "{PLAYER}, por favor?$"

MauvilleCity_Text_WallyMyUncleWontKnowImStrong::
# 315 "data/text/story_dialogue.pory"
	.string "Pero… {PAUSE 5}Pero si no combatimos, mi Tío no\n"
	.string "me dejará combatir en los Gimnasios…$"

MauvilleCity_Text_UncleCanYouBattleWally::
# 320 "data/text/story_dialogue.pory"
	.string "{PLAYER}, {PAUSE 2}¿Verdad?\p"
	.string "Wally te admira muchísimo, y no querrá\n"
	.string "irse de aquí hasta que tengan una\l"
	.string "batalla, así que, por favor, por su bien\l"
	.string "y por el mío, {PAUSE 2}¿Podrías hacerlo?$"

MauvilleCity_Text_WallyPleaseBattleMe::
# 328 "data/text/story_dialogue.pory"
	.string "¡Porfa, {PLAYER}, porfa!$"

MauvilleCity_Text_WallyHereICome::
# 332 "data/text/story_dialogue.pory"
	.string "Gracias, muchas gracias.\p"
	.string "-inhala-, -suspira-… Entonces…\p"
	.string "¡{PLAYER}, t-{PAUSE 1}te desafío a una {PLAY_SE SE_PIN}Batalla\n"
	.string "Pokémon!{WAIT_SE}$"

MauvilleCity_Text_WallyDefeat::
# 339 "data/text/story_dialogue.pory"
	.string "Wally: … {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "Perdí…\p"
	.string "Y en frente de {PLAYER}…$"

MauvilleCity_Text_WallyIllGoBackToVerdanturf::
# 345 "data/text/story_dialogue.pory"
	.string "T-{PAUSE 2}tío… {PAUSE 5}Q-{PAUSE 2}quiero… Ir a Verdanturf…\p"
	.string "… … … … …$"

MauvilleCity_Text_ThankYouNotEnoughToBattle::
# 350 "data/text/story_dialogue.pory"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "G-{PAUSE 2}gr…{PAUSE 2}{TEXT_SPEED 2}gra…{PAUSE 2}gracias, {PLAYER}…\p"
	.string "{TEXT_SPEED 0}Y-{PAUSE 2}yo… {PAUSE 5}R-{PAUSE 2}realme… {PAUSE 5}…{PAUSE 1}…{PAUSE 1}…{PAUSE 1}… {PAUSE 5}{TEXT_SPEED 2}Aprecio\n"
	.string "que… {PAUSE 5}{TEXT_SPEED 2}Te hayas tomado el tiempo de\l"
	.string "{TEXT_SPEED 0}enseñarme que ser Entrenador se trata\l"
	.string "de mucho más que subir unos niveles…\p"
	.string "Necesito…\n"
	.string "… {PAUSE 5}…\l"
	.string "… {PAUSE 5}{TEXT_SPEED 3}Talento, {PAUSE 2}¿Verdad?$"

MauvilleCity_Text_UncleNoNeedToBeDown::
# 362 "data/text/story_dialogue.pory"
	.string "¿Ves, Wally? Tu padre tiene razón.\p"
	.string "No puedes con esto, es demasiado para\n"
	.string "tí.\p"
	.string "No quiero que seguir perdiendo de\n"
	.string "lastime aún más.\p"
	.string "Deja esta locura de ser Entrenador,\n"
	.string "Wally.$"

MauvilleCity_Text_WallyNoNeedTo::
# 369 "data/text/story_dialogue.pory"
	.string "{TEXT_SPEED 2}Iré solo a Verdanturf.\p"
	.string "Necesito pensar, Tío.$"

MauvilleCity_Text_WallysUncleItsOkay::
# 373 "data/text/story_dialogue.pory"
	.string "Está bien, Wally.\n"
	.string "Cuídate mucho.$"

MauvilleCity_Text_UncleVisitUsSometime::
# 377 "data/text/story_dialogue.pory"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "Esto es lo que temíamos, {PLAYER},\n"
	.string "Wally no soporta la derrota…\p"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "Espero que esto al menos le ayude a\n"
	.string "despertarse.\l"
	.string "Ahora dejará esto de lado, y la derrota\l"
	.string "no lo lastimará más. Gracias, {PLAYER}.$"

MauvilleCity_Text_WallyPokenavCall::
# 385 "data/text/story_dialogue.pory"
	.string "… … …\n"
	.string "… … …\n"
	.string "… … …\l"
	.string "… …\l"
	.string "{PAUSE 2}¡Biip!\p"
	.string "Wally:\n"
	.string "¡H-{PAUSE 2}hola,\l"
	.string "{PLAYER}!\p"
	.string "Q-{PAUSE 2}quería\n"
	.string "decirte\l"
	.string "que mi\l"
	.string "Tío\l"
	.string "me\l"
	.string "compró\l"
	.string "un\l"
	.string "PokéNav.\p"
	.string "Ahora\n"
	.string "podré\l"
	.string "hablar\l"
	.string "contigo\l"
	.string "un\l"
	.string "poco\l"
	.string "más\l"
	.string "seguido.\p"
	.string "C-{PAUSE 2}c-{PAUSE 2}c-{PAUSE 2}c-{PAUSE 2}claro,\n"
	.string "s-{PAUSE 2}si\l"
	.string "eso\l"
	.string "n-{PAUSE 2}no\l"
	.string "te\l"
	.string "parece\l"
	.string "m-{PAUSE 2}molesto…\p"
	.string "…\p"
	.string "¿Te\n"
	.string "parece\l"
	.string "bien?\l"
	.string "¡Genial!\p"
	.string "¡Hablamos\n"
	.string "luego,\l"
	.string "{PLAYER}!\p"
	.string "… … …\n"
	.string "… … …\n"
	.string "… … …\l"
	.string "… …\l"
	.string "{PAUSE 2}¡Click!$"

MauvilleCity_Text_RegisteredWally::
# 400 "data/text/story_dialogue.pory"
	.string "Has añadido a Wally\n"
	.string "al PokéNav.$"

MauvilleCity_Text_ScottAParentShould::
# 405 "data/text/story_dialogue.pory"
	.string "Oiga, con el debido respeto,\n"
	.string "{COLOR LIGHT_GRAY SHADOW WHITE}osea, ninguno,{COLOR DARK_GRAY SHADOW LIGHT_GRAY}\l"
	.string "¿Quién se cree usted para hablarle así\l"
	.string "a UN NIÑO? ¿Sobretodo su propio\l"
	.string "sobrino?\p"
	.string "No quiero faltar el respeto, sir, pero un\n"
	.string "tío debería apoyar a su sobrino, no\l"
	.string "tirarlo abajo del modo que lo hizo.$"

MauvilleCity_Text_AndWhoAreYou::
# 411 "data/text/story_dialogue.pory"
	.string "¿Y quién es usted para decirme cómo\n"
	.string "tratar a mi sobrino?$"

MauvilleCity_Text_ImScott::
# 415 "data/text/story_dialogue.pory"
	.string "¿Yo?\p"
	.string "I'm Scott, el {COLOR BLUE}inventor de las Tiendas\n"
	.string "Batalla{COLOR DARK_GRAY}.\p"
	.string "Ah, y más importante para usted, un{COLOR BLUE}\n"
	.string "antiguo Alto Mando de Hoenn{COLOR DARK_GRAY}.$"

MauvilleCity_Text_AndWhyDoICare::
# 420 "data/text/story_dialogue.pory"
	.string "¿Y eso por qué me tiene que importar a\n"
	.string "mí?$"

MauvilleCity_Text_ScottDefendsWally::
# 424 "data/text/story_dialogue.pory"
	.string "Porque digamos que viví lo mismo que\n"
	.string "Wally, y por experiencia le digo que\l"
	.string "tratar de “proteger” a un familiar del\l"
	.string "fracaso…\p"
	.string "… Lo lastimará más que la más\n"
	.string "aplastante derrota. ¿Acaba de perder y\l"
	.string "usted le dice que no sirve para esto?\p"
	.string "¿Qué clase de adulto cree que eso\n"
	.string "ayudará a su sobrino?$"

MauvilleCity_Text_YouDontUnderstand::
# 430 "data/text/story_dialogue.pory"
	.string "Usted no lo entiende, Wally es…\n"
	.string "“Especial,” no podemos dejarlo sin\l"
	.string "supervisión.\p"
	.string "Y veo que no cambiaré su parecer, así\n"
	.string "que me voy.$"

MauvilleCity_Text_Although::
# 435 "data/text/story_dialogue.pory"
	.string "… … … … … Aunque…\p"
	.string "… Se ve bastante feliz junto a los\n"
	.string "Pokémon…\p"
	.string "Debería hablar con su padre sobre esto,\n"
	.string "y detenrlo de…$"

MauvilleCity_Text_ScottBadFamily::
# 441 "data/text/story_dialogue.pory"
	.string "Lo peor de los familiares como él, es que\n"
	.string "vienen de un lugar de preocupación.\p"
	.string "Don't wanna assume, pero parece que su\n"
	.string "padre es peor…$"

MauvilleCity_Text_ScottYoureTheRealDeal::
# 446 "data/text/story_dialogue.pory"
	.string "Anyways…\p"
	.string "Parece que en serio eres buen{OA} en esto,\n"
	.string "¿y buen{A} amig{OA}, también?\p"
	.string "Espero sigas mejorando, ¡Estaré\n"
	.string "esperando ver en quién se convierten\l"
	.string "ambos!$"
