# 984 "data/text/story_dialogue.pory"


Common_Text_Suspense::
# 2 "data/text/story_dialogue.pory"
	.string "{TEXT_SPEED 5}…………………………\n…………………………\l…………………………$"

Common_Text_Realization::
# 6 "data/text/story_dialogue.pory"
	.string "{TEXT_SPEED 2}…………………………\n{PLAY_SE SE_PIN}……!$"

SlateportCity_SternsShipyard_1F_Text_CantMakeHeadsOrTails::
# 14 "data/text/story_dialogue.pory"
	.string "A ver… Si esto va aquí y aquello va\n"
	.string "allá…\p"
	.string "¿Dónde va esto entonces?\n"
	.string "¡Ahhh! ¡Ese tipo y su letra de doctor!$"

SlateportCity_SternsShipyard_1F_Text_MeetDockDeliverToStern::
# 30 "data/text/story_dialogue.pory"
	.string "¿Eh?\n"
	.string "Ah, hola, soy Dock Muéllez.\p"
	.string "El Capitán Stern me ha encargado que\n"
	.string "diseñe un ferry.\p"
	.string "Oh, eso de ahí…\n"
	.string "¿Son las Partes Devon?\p"
	.string "Deben ser para él. El tipo las NECESITA,\n"
	.string "no paraba de murmurarlo.\p"
	.string "¿Puedes ir a buscarlo? Creo que andaba\n"
	.string "por el Museo Océanico buscando\l"
	.string "inspiración.$"

SlateportCity_SternsShipyard_1F_Text_CouldYouFindStern::
# 50 "data/text/story_dialogue.pory"
	.string "¿Que adónde puede haber ido el\n"
	.string "Capitán?\p"
	.string "Debe estar en el Museo, ¿Puedes ir\n"
	.string "entregarle ese paquete?$"

SlateportCity_SternsShipyard_1F_Text_CouldUseAdviceFromVeteran::
# 64 "data/text/story_dialogue.pory"
	.string "Construir barcos es todo un arte.\p"
	.string "Hay mucho que no se resolver con\n"
	.string "cálculos.\p"
	.string "Cómo me gustaría que algún lindo lobo\n"
	.string "de mar me aconsejase…$"

SlateportCity_SternsShipyard_1F_Text_BrineyJoinedUs::
# 80 "data/text/story_dialogue.pory"
	.string "¡Hola! El Señor Briney se ha unido a\n"
	.string "nosotros.\p"
	.string "Gracias a su valiosísima ayuda, nuestro\n"
	.string "proyecto de ferry empieza a tomar\l"
	.string "forma.$"

SlateportCity_SternsShipyard_1F_Text_FerryIsReady::
# 94 "data/text/story_dialogue.pory"
	.string "¡El ferry está listo!\p"
	.string "¡El nuevo S.S. MAREA es toda una\n"
	.string "maravilla tecnológica!\p"
	.string "Sin embargo, creo que aún podemos\n"
	.string "mejorar el diseño.\p"
	.string "¡Ya sabes que el avance de la ciencia es\n"
	.string "imparable!$"

SlateportCity_SternsShipyard_1F_Text_DecidedToHelpDock::
# 114 "data/text/story_dialogue.pory"
	.string "¡Anda, {PLAYER}{KUN}!\n"
	.string "¡Cuánto tiempo!\p"
	.string "Desde que te conocí, me he\n"
	.string "sentido la mar de inquieto.\p"
	.string "Así que he decidido ayudar a\n"
	.string "MUÉLLEZ a construir el ferry.\p"
	.string "¡Imagina cuánta gente podría\n"
	.string "transportar en cada viaje!\p"
	.string "¿Sabes? Este MUÉLLEZ es\n"
	.string "un tipo especial de verdad.\p"
	.string "Uniendo sus conocimientos\n"
	.string "y mi experiencia, haremos\l"
	.string "un gran barco, ¡ya lo creo!$"

SlateportCity_SternsShipyard_1F_Text_SeaIsLikeLivingThing::
# 149 "data/text/story_dialogue.pory"
	.string "Las estaciones, el tiempo,\n"
	.string "la posición de la Luna…\p"
	.string "El estado del mar se ve afectado\n"
	.string "por todo esto y mucho más.\p"
	.string "¡Exactamente!\n"
	.string "¡El mar tiene vida!$"

SlateportCity_SternsShipyard_1F_Text_GetSeasickEasily::
# 171 "data/text/story_dialogue.pory"
	.string "Me entra mareo con nada…, así que\n"
	.string "me han destinado a este puesto.$"

SlateportCity_OceanicMuseum_2F_Text_ShouldI::
# 184 "data/text/story_dialogue.pory"
	.string "{COLOR BLUE}(¿Debería dárselas...?)\p"
	.string "(Supongo que no hay de otra, dejando\n"
	.string "dudas de lado.){COLOR DARK_GRAY}$"

SlateportCity_OceanicMuseum_2F_Text_WeCantDoThat::
# 188 "data/text/story_dialogue.pory"
	.string "¡Tienes sólo un Pokémon!\p"
	.string "¡No podemos atacar a alguien así!$"

SlateportCity_OceanicMuseum_2F_Text_WeCantBeatUp::
# 192 "data/text/story_dialogue.pory"
	.string "¿Lo habrá hecho a propósito?\n"
	.string "¿Para que no l{OA} ataquen?\p"
	.string "¡Arceus, ¿qué pensará el Jefe?!\n"
	.string "¡Esas Partes son nuestras!$"

SlateportCity_OceanicMuseum_2F_Text_BeReady::
# 196 "data/text/story_dialogue.pory"
	.string "Okay, Stern, cálmate. Todo estará bien...$"

SlateportCity_OceanicMuseum_2F_Text_ThankYouForTheParts::
# 200 "data/text/story_dialogue.pory"
	.string "Ah, hola, ¿Eres {ELLA} repartidor{A}?\n"
	.string "Puedes dejarme las Partes por ahí,\l"
	.string "este lugar es peligroso ahora.$"

SlateportCity_OceanicMuseum_2F_Text_WellTakeThoseParts::
# 205 "data/text/story_dialogue.pory"
	.string "{COLOR LIGHT_GRAY SHADOW WHITE}¿Cómo era? Ah, sí, ok. {COLOR DARK_GRAY SHADOW LIGHT_GRAY}\p"
	.string "¡Alto ahí, señores!\n"
	.string "¡Nos llevaremos esas Partes!$"

SlateportCity_OceanicMuseum_2F_Text_SternWhoAreYou::
# 210 "data/text/story_dialogue.pory"
	.string "¡Oh! ¡Eh! ¿Qué?\n"
	.string "¿Q-quiénes son?$"

SlateportCity_OceanicMuseum_2F_Text_WereTeamAqua::
# 215 "data/text/story_dialogue.pory"
	.string "¡Somos el Equipo Aqua!\p"
	.string "¡Y nuestro Jefe nos envió a buscar esas\n"
	.string "Partes!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt1Defeat::
# 220 "data/text/story_dialogue.pory"
	.string "¡Aaaahh!\n"
	.string "¡Me ganó un{A} niñ{OA}!$"

SlateportCity_OceanicMuseum_2F_Text_BossGoingToBeFurious::
# 225 "data/text/story_dialogue.pory"
	.string "¿Porqué tenía que pasar esto…?\n"
	.string "El Jefe no estará complacido…$"

SlateportCity_OceanicMuseum_2F_Text_LetMeTakeCareOfThis::
# 230 "data/text/story_dialogue.pory"
	.string "¡Pedazo de idiota!\n"
	.string "¡Se suponía que atacáramos juntos!\p"
	.string "¡Ven conmigo, aún con esos Pokémon\n"
	.string "débiles de tus reservas seremos más\l"
	.string "fuertes!$"

SlateportCity_OceanicMuseum_2F_Text_LetMeTakeCareOfThis2::
# 235 "data/text/story_dialogue.pory"
	.string "¡Prerárate!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt2Defeat::
# 239 "data/text/story_dialogue.pory"
	.string "Recluta 1: ¡¿QUÉ?!\n"
	.string "Recluta 2: ¡Ja! El problema\l"
	.string "no era yo.$"

SlateportCity_OceanicMuseum_2F_Text_MeddlingKid::
# 244 "data/text/story_dialogue.pory"
	.string "¿Ahora qué? Se supone que las Partes\n"
	.string "son nuestras, ¡Esto es injusto!$"

SlateportCity_OceanicMuseum_2F_Text_CameToSeeWhatsTakingSoLong::
# 249 "data/text/story_dialogue.pory"
	.string "Sabía que no se podía confiar en Stern,\n"
	.string "¿pero en ustedes?\p"
	.string "¡No pensé que perderían ante un{A} niñ{OA}!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWarning::
# 254 "data/text/story_dialogue.pory"
	.string "¡Escúchame bien, vamos a cambiar el\n"
	.string "mundo!\p"
	.string "¡Yo, {COLOR BLUE}el Líder del Equipo{COLOR DARK_GRAY},\n"
	.string "{COLOR BLUE}el Grandioso Archie{COLOR DARK_GRAY}, te lo aseguro!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWarning2::
# 259 "data/text/story_dialogue.pory"
	.string "En pocos años, llegaremos {COLOR BLUE}a un punto\n"
	.string "sin retorno{COLOR DARK_GRAY}, uno donde nuestras\l"
	.string "acciones dejarán este mundo\l"
	.string "inhabitable.\p"
	.string "Todos aquí en Slateport lo saben, ¡Pero\n"
	.string "mi Equipo Aqua salvará el mundo!\p"
	.string "Tengo que admitirlo…\p"
	.string "Tienes agallas por meterte con\n"
	.string "nosotros, ¡Pero para la próxima, te\l"
	.string "dejaré naufragando!$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWereLeaving::
# 264 "data/text/story_dialogue.pory"
	.string "¡Ahora, ustedes dos!\n"
	.string "¡Nos vamos!\p"
	.string "Díganle a todos que nos vamos a las\n"
	.string "aguas termales, lo merecen.\p"
	.string "Algo me dice que ya recuperaremos las\n"
	.string "Partes.$"

SlateportCity_OceanicMuseum_2F_Text_SternThankYouForSavingUs::
# 270 "data/text/story_dialogue.pory"
	.string "Ese {COLOR BLUE}Equipo Aqua{COLOR DARK_GRAY}… …\n"
	.string "¡Entrar a la fuerza y atacar a un{A} niñ{OA}!\p"
	.string "No puedo creer que esta ciudad esté\n"
	.string "tan de acuerdo con criminales que\l"
	.string "dicen “ayudar,”\l"
	.string "¡Cuando en verdad son un peligro!\p"
	.string "Pero bueno, ¡Me llevaré las Partes,\n"
	.string "gracias!$"

SlateportCity_OceanicMuseum_2F_Text_SternIveGotToGo::
# 278 "data/text/story_dialogue.pory"
	.string "Estas Partes son necesarias para la\n"
	.string "construcción de un {COLOR BLUE}submarino{COLOR DARK_GRAY} que\l"
	.string "inventé…$"

MauvilleCity_Text_UncleHesTooPeppy::
# 285 "data/text/story_dialogue.pory"
	.string "Mi Wally se emociona mucho, gracias a\n"
	.string "los Pokémon.\p"
	.string "Me parece que es mucha emoción…$"

MauvilleCity_Text_WallyWantToChallengeGym::
# 291 "data/text/story_dialogue.pory"
	.string "¡Ay, porfa, Tío, déjame tomar el {COLOR BLUE}Desafío\n"
	.string "de los Gimnasios{COLOR DARK_GRAY}, ya soy muy fuerte!\p"
	.string "¡Ralts y yo aprendimos técnicas súper\n"
	.string "fuertes!$"

MauvilleCity_Text_UncleYourePushingIt::
# 298 "data/text/story_dialogue.pory"
	.string "Wally, Wally, tranquilo.\p"
	.string "¿No te estás precipitando?{PAUSE 2} Entiendo\n"
	.string "que se hayan fortalecido, pero los\l"
	.string "{COLOR BLUE}Líderes de Gimnasio{COLOR DARK_GRAY} son MUY fuertes…$"

MauvilleCity_Text_WallyWeCanBeatAnyone::
# 305 "data/text/story_dialogue.pory"
	.string "¡No me estoy precipitando, Tío!\p"
	.string "Si Ralts me ayuda, {PAUSE 5}¡Podré vencer a\n"
	.string "cualquier rival!$"

MauvilleCity_Text_WallyWillYouBattleMe::
# 311 "data/text/story_dialogue.pory"
	.string "Ah, {PAUSE 2}¡{PLAYER}, {PLAYER}!\p"
	.string "¡Hace tanto que no te veo, amig{OA}!\p"
	.string "¡{PLAYER}, {PLAYER}, quiero\n"
	.string "mostrarte lo fuerte que me he vuelto!\l"
	.string "Mi Ralts hasta ha aprendido muchos\l"
	.string "ataques nuevos, {PLAYER}.\p"
	.string "¿Te gustaría combatir conmigo,\n"
	.string "{PLAYER}, por favor?$"

MauvilleCity_Text_WallyMyUncleWontKnowImStrong::
# 322 "data/text/story_dialogue.pory"
	.string "Pero… {PAUSE 5}Pero si no combatimos, mi Tío no\n"
	.string "me dejará combatir en los Gimnasios…$"

MauvilleCity_Text_UncleCanYouBattleWally::
# 327 "data/text/story_dialogue.pory"
	.string "{PLAYER}, {PAUSE 2}¿Verdad?\p"
	.string "Wally te admira muchísimo, y no querrá\n"
	.string "irse de aquí hasta que tengan una\l"
	.string "batalla, así que, por favor, por su\l"
	.string "bien\l"
	.string "y por el mío, {PAUSE 2}¿Podrías hacerlo?$"

MauvilleCity_Text_WallyPleaseBattleMe::
# 335 "data/text/story_dialogue.pory"
	.string "¡Porfa, {PLAYER}, porfa!$"

MauvilleCity_Text_WallyHereICome::
# 339 "data/text/story_dialogue.pory"
	.string "Gracias, muchas gracias.\p"
	.string "-inhala-, -suspira-… Entonces…\p"
	.string "¡{PLAYER}, t-{PAUSE 1}te desafío a una {PLAY_SE SE_PIN}Batalla\n"
	.string "Pokémon!{WAIT_SE}$"

MauvilleCity_Text_WallyDefeat::
# 346 "data/text/story_dialogue.pory"
	.string "Wally: … {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "Perdí…\p"
	.string "Y en frente de {PLAYER}…$"

MauvilleCity_Text_WallyIllGoBackToVerdanturf::
# 352 "data/text/story_dialogue.pory"
	.string "T-{PAUSE 2}tío… {PAUSE 5}Q-{PAUSE 2}quiero… Ir a Verdanturf…\p"
	.string "… … … … …$"

MauvilleCity_Text_ThankYouNotEnoughToBattle::
# 357 "data/text/story_dialogue.pory"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "G-{PAUSE 2}gr…{PAUSE 2}{TEXT_SPEED 2}gra…{PAUSE 2}gracias, {PLAYER}…\p"
	.string "{TEXT_SPEED 0}Y-{PAUSE 2}yo… {PAUSE 5}R-{PAUSE 2}realme… {PAUSE 5}…{PAUSE 1}…{PAUSE 1}…{PAUSE 1}… {PAUSE 5}{TEXT_SPEED 2}Aprecio\n"
	.string "que… {PAUSE 5}{TEXT_SPEED 2}Te hayas tomado el tiempo de\l"
	.string "{TEXT_SPEED 0}enseñarme que ser Entrenador se\l"
	.string "trata\l"
	.string "de mucho más que subir unos niveles…\p"
	.string "Necesito…\n"
	.string "… {PAUSE 5}…\l"
	.string "… {PAUSE 5}{TEXT_SPEED 3}Talento, {PAUSE 2}¿Verdad?$"

MauvilleCity_Text_UncleNoNeedToBeDown::
# 369 "data/text/story_dialogue.pory"
	.string "¿Ves, Wally? Tu padre tiene razón.\p"
	.string "No puedes con esto, es demasiado para\n"
	.string "tí.\p"
	.string "No quiero que seguir perdiendo de\n"
	.string "lastime aún más.\p"
	.string "Deja esta locura de ser Entrenador,\n"
	.string "Wally.$"

MauvilleCity_Text_WallyNoNeedTo::
# 376 "data/text/story_dialogue.pory"
	.string "{TEXT_SPEED 2}Iré solo a Verdanturf.\p"
	.string "Necesito pensar, Tío.$"

MauvilleCity_Text_WallysUncleItsOkay::
# 380 "data/text/story_dialogue.pory"
	.string "Está bien, Wally.\n"
	.string "Cuídate mucho.$"

MauvilleCity_Text_UncleVisitUsSometime::
# 384 "data/text/story_dialogue.pory"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "Esto es lo que temíamos, {PLAYER},\n"
	.string "Wally no soporta la derrota…\p"
	.string "… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}… {PAUSE 5}…\p"
	.string "Espero que esto al menos le ayude a\n"
	.string "despertarse.\l"
	.string "Ahora dejará esto de lado, y la\l"
	.string "derrota no lo lastimará más. Gracias,\l"
	.string "{PLAYER}.$"

MauvilleCity_Text_WallyPokenavCall::
# 392 "data/text/story_dialogue.pory"
	.string "… … …\n"
	.string "… …\l"
	.string "…\n"
	.string "… …\l"
	.string "… …\l"
	.string "…\l"
	.string "{PAUSE 2}¡Biip!\p"
	.string "Wally:\n"
	.string "¡H-{PAUSE 2}hola,\l"
	.string "{PLAYER}!\p"
	.string "Q-{PAUSE 2}quería\n"
	.string "decirte\l"
	.string "que\l"
	.string "mi\l"
	.string "Tío\l"
	.string "me\l"
	.string "compró\l"
	.string "un\l"
	.string "PokéNav.\p"
	.string "Ahora\n"
	.string "podré\l"
	.string "hablar\l"
	.string "contigo\l"
	.string "un\l"
	.string "poco\l"
	.string "más\l"
	.string "seguido.\p"
	.string "C-{PAUSE 2}c-{PAUSE 2}c-{PAUSE 2}c-{PAUSE 2}claro,\n"
	.string "s-{PAUSE 2}si\l"
	.string "eso\l"
	.string "n-{PAUSE 2}no\l"
	.string "te\l"
	.string "parece\l"
	.string "m-{PAUSE 2}molesto…\p"
	.string "…\p"
	.string "¿Te\n"
	.string "parece\l"
	.string "bien?\l"
	.string "¡Genial!\p"
	.string "¡Hablamos\n"
	.string "luego,\l"
	.string "{PLAYER}!\p"
	.string "… … …\n"
	.string "… …\l"
	.string "…\n"
	.string "… …\l"
	.string "… …\l"
	.string "…\l"
	.string "{PAUSE 2}¡Click!$"

MauvilleCity_Text_RegisteredWally::
# 407 "data/text/story_dialogue.pory"
	.string "Has añadido a Wally\n"
	.string "al PokéNav.$"

MauvilleCity_Text_ScottAParentShould::
# 412 "data/text/story_dialogue.pory"
	.string "Oiga, con el debido respeto,\n"
	.string "{COLOR LIGHT_GRAY SHADOW WHITE}osea, ninguno,{COLOR DARK_GRAY SHADOW LIGHT_GRAY}\l"
	.string "¿Quién se cree usted para hablarle\l"
	.string "así a UN NIÑO? ¿Sobretodo su propio\l"
	.string "sobrino?\p"
	.string "No quiero faltar el respeto, sir, pero un\n"
	.string "tío debería apoyar a su sobrino, no\l"
	.string "tirarlo abajo del modo que lo hizo.$"

MauvilleCity_Text_AndWhoAreYou::
# 418 "data/text/story_dialogue.pory"
	.string "¿Y quién es usted para decirme cómo\n"
	.string "tratar a mi sobrino?$"

MauvilleCity_Text_ImScott::
# 422 "data/text/story_dialogue.pory"
	.string "¿Yo?\p"
	.string "I'm Scott, el {COLOR BLUE}inventor de las Tiendas\n"
	.string "Batalla{COLOR DARK_GRAY}.\p"
	.string "Ah, y más importante para usted, un{COLOR BLUE}\n"
	.string "antiguo Alto Mando de Hoenn{COLOR DARK_GRAY}.$"

MauvilleCity_Text_AndWhyDoICare::
# 427 "data/text/story_dialogue.pory"
	.string "¿Y eso por qué me tiene que importar a\n"
	.string "mí?$"

MauvilleCity_Text_ScottDefendsWally::
# 431 "data/text/story_dialogue.pory"
	.string "Porque digamos que viví lo mismo que\n"
	.string "Wally, y por experiencia le digo que\l"
	.string "tratar de “proteger” a un familiar del\l"
	.string "fracaso…\p"
	.string "… Lo lastimará más que la más\n"
	.string "aplastante derrota. ¿Acaba de perder\l"
	.string "y usted le dice que no sirve para\l"
	.string "esto?\p"
	.string "¿Qué clase de adulto cree que eso\n"
	.string "ayudará a su sobrino?$"

MauvilleCity_Text_YouDontUnderstand::
# 437 "data/text/story_dialogue.pory"
	.string "Usted no lo entiende, Wally es…\n"
	.string "“Especial,” no podemos dejarlo sin\l"
	.string "supervisión.\p"
	.string "Y veo que no cambiaré su parecer, así\n"
	.string "que me voy.$"

MauvilleCity_Text_Although::
# 442 "data/text/story_dialogue.pory"
	.string "… … … … … Aunque…\p"
	.string "… Se ve bastante feliz junto a los\n"
	.string "Pokémon…\p"
	.string "Debería hablar con su padre sobre esto,\n"
	.string "y detenrlo de…$"

MauvilleCity_Text_ScottBadFamily::
# 448 "data/text/story_dialogue.pory"
	.string "Lo peor de los familiares como él, es que\n"
	.string "vienen de un lugar de preocupación.\p"
	.string "Don't wanna assume, pero parece que su\n"
	.string "padre es peor…$"

MauvilleCity_Text_ScottYoureTheRealDeal::
# 453 "data/text/story_dialogue.pory"
	.string "Anyways…\p"
	.string "Parece que en serio eres buen{OA} en esto,\n"
	.string "¿y buen{A} amig{OA}, también?\p"
	.string "Espero sigas mejorando, ¡Estaré\n"
	.string "esperando ver en quién se convierten\l"
	.string "ambos!$"

Route112_Text_LeaderGoingToAwakenThing::
# 462 "data/text/story_dialogue.pory"
	.string "Ey, lindo, ¿En serio {COLOR BLUE}nuestro Líder va a\n"
	.string "despertar a {TEXT_SPEED 2}ESA cosa{COLOR DARK_GRAY}?$"

Route112_Text_YeahWeNeedMeteorite::
# 466 "data/text/story_dialogue.pory"
	.string "Sí, amor. Pero necesitamos el Meteorito.$"

Route112_Text_OhThatsWhyCrewWentToFallarbor::
# 470 "data/text/story_dialogue.pory"
	.string "Por eso se fueron a Fallarbor, supongo.$"

Route112_Text_CantLetAnyonePassUntilTheyreBack::
# 474 "data/text/story_dialogue.pory"
	.string "Sí, llegamos un poco tarde, pero con\n"
	.string "algo de suerte, nadie pasó.\p"
	.string "No dejaremos pasar a nadie desde ahora.$"

Route112_Text_AreYouChallengingUs::
# 478 "data/text/story_dialogue.pory"
	.string "¿Qué pasa? ¿Nos estás retando?$"

Route112_Text_WerePlentyStrong::
# 482 "data/text/story_dialogue.pory"
	.string "Somos fuertes, no te lo recomiendo...\n"
	.string "¡Nuestros Pokémon son nivel 45!$"

Route112_Text_WhatWhereAreYou::
# 486 "data/text/story_dialogue.pory"
	.string "¿¡QUÉ!?\n"
	.string "¿¡A dónde te vas!?\p"
	.string "¡Vas a dormir en el sillón, pedazo de\n"
	.string "cobarde!$"

Route112_Text_HeyDontGoThere::
# 490 "data/text/story_dialogue.pory"
	.string "¡Y tú!\p"
	.string "¿¡Qué crees que estás-!?$"

Route112_Text_WeToldYou::
# 494 "data/text/story_dialogue.pory"
	.string "Deberías habernos creído. Ahora vete.\n"
	.string "No molestes.$"

Route112_Text_WeCanDoBetter::
# 498 "data/text/story_dialogue.pory"
	.string "Y eso que ni trajimos nuestros Pokémon\n"
	.string "más fuertes.$"

MtChimney_Text_MaxieFreakOut::
# 504 "data/text/story_dialogue.pory"
	.string "¿Cómo que no lo tienen?\p"
	.string "¿¡DÓNDE ESTÁ, ENTONCES!?$"

MtChimney_Text_TabithaWeDontKnow::
# 515 "data/text/story_dialogue.pory"
	.string "¡N-{PAUSE 8}no sabemos, Señor! ¡N-{PAUSE 8}nunca nos\n"
	.string "llegó!$"

MtChimney_Text_CourtneySolution::
# 526 "data/text/story_dialogue.pory"
	.string "Señor. Debemos buscar una solución.\n"
	.string "Actualmente lo estoy haciendo.$"

MtChimney_Text_MaxieFreakOut2::
# 537 "data/text/story_dialogue.pory"
	.string "¡No, no, no, {SHAKE_SCREEN 4 4 2 3}NO!\p"
	.string "¡NINGUNO {SHAKE_SCREEN 1 1 3 0}ENTIENDE!\p"
	.string "ME FALLARON. Y esta máquina… No creo\n"
	.string "que funcione…\p"
	.string "Así que aunque no hubieran {SHAKE_SCREEN 3 4 2 2}FRACASADO,\n"
	.string "aún perderíamos.\p"
	.string "……………\n"
	.string "…………\p"
	.string "{COLOR BLUE}(Sigo fallando, {COLOR RED}sin importar qué haga{COLOR BLUE},\n"
	.string "¿No?)$"

MtChimney_Text_MaxieNoticePlayer::
# 550 "data/text/story_dialogue.pory"
	.string "Y por si no fuera ya demasiado…\n"
	.string "¿Quién dejó pasar a est{EA} niñ{OA}?\p"
	.string "¡Les dije que evacúen el lugar!\p"
	.string "No importa, me ocuparé de esto yo.$"

MtChimney_Text_ArchieAsIf::
# 562 "data/text/story_dialogue.pory"
	.string "{SHAKE_SCREEN 2 3 2 1}¡Como si te fuera a dejar!$"

MtChimney_Text_MaxieDefeat::
# 573 "data/text/story_dialogue.pory"
	.string "¡¿Qué?!\p"
	.string "¡¿Me han derrotado, al gran Maxie!?$"

MtChimney_Text_ArchieKnewYouCould::
# 584 "data/text/story_dialogue.pory"
	.string "{SHAKE_SCREEN 2 3 2 1}¡Sabía que podías!$"

MtChimney_Text_ArchieBattleWithPlayer::
# 595 "data/text/story_dialogue.pory"
	.string "¡{PLAYER}! ¡Unamos fuerzas y\n"
	.string "derrotemos a Maxie!\p"
	.string "¡No dejaré que un adulto ataque así a\n"
	.string "un{A} niñ{OA}!$"

MtChimney_Text_DeltaPlan1::
# 607 "data/text/story_dialogue.pory"
	.string "¿Tienes todo?$"

MtChimney_Text_DeltaPlan2::
# 611 "data/text/story_dialogue.pory"
	.string "Sí, quédate aquí mientras la\n"
	.string "reprogramo.$"

MtChimney_Text_DeltaYouCantPass::
# 615 "data/text/story_dialogue.pory"
	.string "Ni lo pienses.\n"
	.string "No puedes pasar. Punto final.$"

MtChimney_Text_DeltaWereDoneHere::
# 619 "data/text/story_dialogue.pory"
	.string "¿Un{A} intrus{OA}?\n"
	.string "Qué ternura.\p"
	.string "Vámonos, ya terminamos.$"

MtChimney_Text_MaxieArrive::
# 623 "data/text/story_dialogue.pory"
	.string "¡Entren todos! ¡A sus posiciones!$"

MtChimney_Text_MaxieWhoAreYou::
# 627 "data/text/story_dialogue.pory"
	.string "¿¡Y tú quién eres!?\p"
	.string "Pareces un{A} Entrenador{A}. Supongo no te\n"
	.string "irás hasta que te derrote,\l"
	.string "¡Te arrepentirás de encontrarte con\l"
	.string "{COLOR BLUE}Maxie{COLOR DARK_GRAY},{COLOR BLUE} el Líder del Equipo Magma{COLOR DARK_GRAY}!$"

MtChimney_Text_MagmaGruntMaxieLost1::
# 631 "data/text/story_dialogue.pory"
	.string "¿Nuestro Líder perdió?$"

MtChimney_Text_MagmaGruntMaxieLost2::
# 635 "data/text/story_dialogue.pory"
	.string "Le dije que trajera su Equipo\n"
	.string "principal...$"

MtChimney_Text_MaxieIllSucceedAnyways::
# 639 "data/text/story_dialogue.pory"
	.string "Seguro crees que venir aquí cambió\n"
	.string "algo, {PAUSE 30}¡Pero no es así!\p"
	.string "¡Con este Meteorito..!$"

MtChimney_Text_MaxieMachineNotWork::
# 643 "data/text/story_dialogue.pory"
	.string "¡Pero!\p"
	.string "¡L-la máquina! ¡Alguien la arruinó!$"

MtChimney_Text_ArchieArrives::
# 647 "data/text/story_dialogue.pory"
	.string "¡Bua-jajaja! ¿¡Quién lo diría!?\p"
	.string "¡No tuvimos ni que hacer nada!$"

MtChimney_Text_ArchieTellsGrunts::
# 651 "data/text/story_dialogue.pory"
	.string "¡Óiganme! ¡Vamos a las aguas termales,\n"
	.string "marineros!\p"
	.string "est{EA} pequeñ{OA} percebe está de nuestro\n"
	.string "lado e hizo el trabajo por nosotros.$"

MtChimney_Text_WeLoveYouArchie::
# 655 "data/text/story_dialogue.pory"
	.string "¡Eres genial, Jefecito!\p"
	.string "¡Te amamos, Archie!$"

MeteorFalls_1F_1R_Text_AndThatsWhy::
# 661 "data/text/story_dialogue.pory"
	.string "Y es por eso… Cuando lleguen…\p"
	.string "Harás lo que te digan.$"

MeteorFalls_1F_1R_Text_Understood::
# 672 "data/text/story_dialogue.pory"
	.string "¡Entendido, Señor!\p"
	.string "Espero no lo noten…$"

MeteorFalls_1F_1R_Text_FamiliarVoice::
# 683 "data/text/story_dialogue.pory"
	.string "{COLOR_PLAYER}(Esa voz…)\n"
	.string "(… ¿Será que… Es {COLOR_RIVAL}él{COLOR_PLAYER}…?)$"

MeteorFalls_1F_1R_Text_WithThisMeteorite::
# 717 "data/text/story_dialogue.pory"
	.string "¡Entregue el meteorito!\n"
	.string "Con él, en el Monte Chimney…$"

MeteorFalls_1F_1R_Text_ThisIsAllIHave::
# 728 "data/text/story_dialogue.pory"
	.string "¡N-no…! ¡Esto es todo lo que tengo!$"

MeteorFalls_1F_1R_Text_PlayerWhatDoIDo::
# 739 "data/text/story_dialogue.pory"
	.string "{COLOR_PLAYER}(¿Y qué hago yo ahora?)$"

MeteorFalls_1F_1R_Text_PlayerRightHelp::
# 750 "data/text/story_dialogue.pory"
	.string "{COLOR_PLAYER}(¡Claro! No puedo abandonarlo así,\n"
	.string "¿Verdad?)$"

MeteorFalls_1F_1R_Text_PlayerRightJustWatch::
# 761 "data/text/story_dialogue.pory"
	.string "{COLOR_PLAYER} (¡Claro! No es mi lugar, ¿Verdad?)$"

MeteorFalls_1F_1R_Text_DontExpectMercyFromMagma::
# 772 "data/text/story_dialogue.pory"
	.string "¿Y est{EA} niñ{OA}?\n"
	.string "¿No serás tú {ELLA} que estuvo derrotando\l"
	.string "al Equipo Aqua?\p"
	.string "¡Verás qué gran poder poseemos en el\n"
	.string "Equipo Magma!$"

MeteorFalls_1F_1R_Text_HoldItRightThereMagma::
# 797 "data/text/story_dialogue.pory"
	.string "¡Alto ahí, Equipo Magma!\p"
	.string "{COLOR BLUE}(Jeje… Siempre quise decir eso…){COLOR DARK_GRAY}\p"
	.string "¡Abandonen el planeta!$"

MeteorFalls_1F_1R_Text_MagmaConfusion::
# 811 "data/text/story_dialogue.pory"
	.string "???????????????????????????????$"

MeteorFalls_1F_1R_Text_GotCarriedAway::
# 815 "data/text/story_dialogue.pory"
	.string "Em… Creo que me pasé…\p"
	.string "Ejem……\n"
	.string "¿Creyeron que podrían salirse con la\l"
	.string "suya sin que les digamos nada?$"

MeteorFalls_1F_1R_Text_WhatIsThisChild::
# 826 "data/text/story_dialogue.pory"
	.string "Q-{PAUSE 5} eh?\p"
	.string "{PAUSE 10}¿¡PERO Y EST{EA} {ITOITA} QUÉ ES!?$"

MeteorFalls_1F_1R_Text_WhatIsThisYOU::
# 837 "data/text/story_dialogue.pory"
	.string "¡Mítico mío, eres IDIOTA!\p"
	.string "Te vivo diciendo, un Ursaring Atacante\n"
	.string "Especial ¡NO. VA. A. FUNCIONAR!\p"
	.string "¿Y cómo hiciste para que tu Nidoking\n"
	.string "conozca Terremoto cuatro veces?$"

MeteorFalls_1F_1R_Text_ShutUp::
# 850 "data/text/story_dialogue.pory"
	.string "¡CÁLLATE! ¡CÁLLATE!\p"
	.string "Primero que nada, este Nidoking me lo\n"
	.string "dio el {COLOR RED}Señor Maxie{COLOR DARK_GRAY}.\l"
	.string "Segundo que nada, ¡MI URSARING VA A\l"
	.string "FUNCIONAR, TE LO ASEGURO!$"

MeteorFalls_1F_1R_Text_BeSeeingYouTeamAqua::
# 863 "data/text/story_dialogue.pory"
	.string "¡Muy tarde, Equipo Aqua!\p"
	.string "¡El Meteorito es nuestro!\p"
	.string "¿Por qué no se vienen al Monte Chimney\n"
	.string "e intentan detenernos?$"

MeteorFalls_1F_1R_Text_ArchieHelpedBeforeNotNow::
# 875 "data/text/story_dialogue.pory"
	.string "Tú. Tú eres {ELLA} {GENDER} que ví en Slateport,\n"
	.string "¿verdad?\p"
	.string "La verdad no te comprendo.\n"
	.string "Al menos una vez, nos ayudaste,\l"
	.string "¿Verdad?\p"
	.string "¿Y ahora estás de SU lado?\p"
	.string "Mira. Piensa lo que quieras, pero no soy\n"
	.string "agresivo. No soy idiota. Ese Eqipo\l"
	.string "Magma es un peligro.\p"
	.string "Mientras no interfieras, y ayudes a\n"
	.string "acabar con el Equipo Magma, no me\l"
	.string "importa lo que hagas.\p"
	.string "Pero te metes en nuestro camino… Y\n"
	.string "preferirás haberte ahogado en el\l"
	.string "océano de camino a Slateport…$"

MeteorFalls_1F_1R_Text_ArchieHelpedBothTimes::
# 894 "data/text/story_dialogue.pory"
	.string "Tú. Tú eres {ELLA} que ví en Slateport,\n"
	.string "¿verdad?\p"
	.string "Parece que estamos en el mismo barco.\n"
	.string "Je, no lo escondas. Te vi robarte el\l"
	.string "Meteorito en ese descuido. Más te\l"
	.string "vale no bajarte de esa nave.\p"
	.string "Vayamos todos al Monte Chimney… Me\n"
	.string "muero de ganas de ver la cara de {COLOR RED}Maxie{COLOR DARK_GRAY}\l"
	.string "cuando se entere.$"

MeteorFalls_1F_1R_Text_ArchieNeverHelped::
# 912 "data/text/story_dialogue.pory"
	.string "Tú. Tú eres {ELLA} {GENDER} que ví en Slateport,\n"
	.string "¿verdad?\p"
	.string "La verdad no te comprendo.\n"
	.string "¿Eres infiltrad{OA} del Equipo Magma,\l"
	.string "verdad?\p"
	.string "¿O simplemente eres idiota? Mira. Piensa\n"
	.string "lo que quieras, pero no actúo sin\l"
	.string "pensar. Ese Eqipo Magma es un peligro.\p"
	.string "Y si te metes en nuestro camino… No\n"
	.string "prometo que haya Centro Pokémon\l"
	.string "capaz de salvar a tus compañeros…$"

MeteorFalls_1F_1R_Text_MeetProfCozmo::
# 930 "data/text/story_dialogue.pory"
	.string "Soy… Cozmo…\n"
	.string "Soy un Profesor Pokémon…\p"
	.string "É-{PAUSE 8}él dijo…{PAUSE 16} ¡C-{PAUSE 8}cl-{PAUSE 8}claro que hablo de ese\n"
	.string "Recluta!\p"
	.string "Me engañó…{PAUSE 16} Y se llevó el Meteorito.\p"
	.string "¿Para qué lo querrán?$"

MeteorFalls_1F_1R_Text_ProfCozmoGiveMeteorite::
# 946 "data/text/story_dialogue.pory"
	.string "¿L-{PAUSE 8}lo tienes?\p"
	.string "{COLOR BLUE}(Esto es terrible…){COLOR DARK_GRAY}\p"
	.string "¡Q-{PAUSE 8}qué bien!\n"
	.string "¿Vamos a mi laboratorio?$"

MeteorFalls_1F_1R_Text_ProfCozmoGetItBack::
# 960 "data/text/story_dialogue.pory"
	.string "¿L-{PAUSE 8}lo recuperarás?\p"
	.string "¡Qué alivio!\n"
	.string "Por favor, ten cuidado con ellos…$"

MeteorFalls_1F_1R_Text_WhatsTeamMagmaDoingAtMtChimney::
# 972 "data/text/story_dialogue.pory"
	.string "Ese tal “Equipo Magma”… ¿Qué Giratinas\n"
	.string "querrán en el Monte Chimney?$"
